# .platform.app.yaml
name: app
type: 'php:8.3'

# Relationships section
relationships:
  mysql: 'mysql:mysql'
  
# Additional settings for the application
build:
  flavor: symfony

# Hook for any build-time actions (optional)
hooks:
  build: |
    echo "Running build steps..."
    composer install --no-dev --optimize-autoloader
