name: app
type: php:8.2
build:
    flavor: none

relationships:
    database: "database:postgresql"

variables:
    php:
        memory_limit: 512M

disk: 2048

mounts:
    "/var": { source: local, source_path: var }

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

hooks:
    build: |
        set -e
        composer install --no-dev --optimize-autoloader
        composer dump-env prod
        APP_ENV=prod APP_DEBUG=0 php bin/console cache:clear
        APP_ENV=prod APP_DEBUG=0 php bin/console cache:warmup
        
    deploy: |
        set -e
        php bin/console doctrine:migrations:migrate --no-interaction
