# .platform.app.yaml
name: routewise
type: 'php:8.3'

# Relationships section
relationships:
  database: 'mysql:mysql'
  
# Additional settings for the application
build:
  flavor: symfony

# Hook for any build-time actions (optional)
hooks:
  build: |ss
    set -e
    composer install --no-dev --optimize-autoloader
    composer dump-env prod
    bin/console cache:clear
    bin/console assets:install --no-debug
  deploy: |
    set -e
    bin/console doctrine:migrations:migrate --no-interaction

# Web settings
web:
  locations:
    "/":
      root: "public"
      expires: 1h
      passthru: "/index.php"

# Disk settings
disk: 512

# Mounts settings
mounts:
  "/var": { source: local, source_path: var }
